# Generated by Django 4.1.4 on 2022-12-14 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Journals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='journal',
            name='slug',
            field=models.SlugField(default='', unique=True),
        ),
    ]
