# Generated by Django 4.1.4 on 2022-12-16 10:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Journals', '0003_journal_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='journal',
            name='publish',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
